# Environment variables
# - HOST_NAME
# - USER_NAME

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "7d:1b:68:f5:b5:b7:76:6c:11:2a:2c:66:70:61:9e:2e"

      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan -p 10022 ${HOST_NAME} >> ~/.ssh/known_hosts

      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --rsh="ssh -p 10022" --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:~/blogee.info/public_html/blogee
            fi
